apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-app
  namespace: nodeport
spec:
  replicas: 3
  selector:
    app: node-app
  template:
    metadata:
      namespace: nodeport
      labels:
        app: node-app
    spec:
      containers:
      - name: node-cnt
        image: terezabisharyan/node-app:v1
        ports:
        - containerPort: 8080
