apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: simple-node
  namespace: cip
spec:
  containers:
  - name: node-app
    image: terezabisharyan/node-app:v1
    ports:
    - containerPort: 8080
      protocol: TCP
